# These are supported funding model platforms

github : [DawallAZllon91, le-pingouin-en-securite, Le-pingouin-en-securite, LePingouinenSecurite]
patreon : DawallAZllon91
personalizado : ["https://www.paypal.me/DawallAZllon91"]
