name: Prevent yarn.lock changes in PRs
on: [pull_request]

jobs:
  main:
    name: Prevent yarn.lock changes in PRs
    runs-on: ubuntu-latest
    steps:
      - uses: octokit/request-action@v2.x
        id: get_permissions
        with:
          route: GET /repos/microsoft/vscode/collaborators/{username}/permission
          username: ${{ github.event.pull_request.user.login }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set control output variable
        id: control
        run: |
          echo "user: ${{ github.event.pull_request.user.login }}"
          echo "role: ${{ fromJson(steps.get_permissions.outputs.data).permission }}"
          echo "is dependabot: ${{ github.event.pull_request.user.login == 'dependabot[bot]' }}"
          echo "should_run: ${{ !contains(fromJson('["admin", "maintain", "write"]'), fromJson(steps.get_permissions.outputs.data).permission) }}"
          echo "should_run=${{ !contains(fromJson('["admin", "maintain", "write"]'), fromJson(steps.get_permissions.outputs.data).permission) && github.event.pull_request.user.login != 'dependabot[bot]' }}" >> $GITHUB_OUTPUT
      - name: Get file changes
        uses: trilom/file-changes-action@ce38c8ce2459ca3c303415eec8cb0409857b4272
        if: ${{ steps.control.outputs.should_run == 'true' }}
      - name: Check for lockfile changes
        if: ${{ steps.control.outputs.should_run == 'true' }}
        run: |
          cat $HOME/files.json | jq -e 'any(test("yarn\\.lock$|Cargo\\.lock$")) | not' \
            || (echo "Changes to yarn.lock/Cargo.lock files aren't allowed in PRs." && exit 1)
            - name: Install Octopus CLI
  # You may pin to the exact commit or the version.
  # uses: OctopusDeploy/install-octopus-cli-action@b44313a25eb0e47b3d726eb7a080e0c5de9186ed
  uses: OctopusDeploy/install-octopus-cli-action@v3.0.0
  with:
    # Octopus CLI version
    version: # optional, default is latest
    
                - name: Octo my README
  # You may pin to the exact commit or the version.
  # uses: arndom/octo-my-readme-workflow@9add6056113f312d1c33c36e9986c0fa1efc45c1
  uses: arndom/octo-my-readme-workflow@v1
  with:
    # user token
    gh_token: # default is ${{ github.token }}
          
                 - name: Octokit.js
  # You may pin to the exact commit or the version.
  # uses: juliangruber/octokit-action@e47ba029b2fd259de3a7e9fc371b0eb4a984dd5e
  uses: juliangruber/octokit-action@v1.0.2

                           - name: OctopusDeploy CLI
  # You may pin to the exact commit or the version.
  # uses: burtonr/octopus-cli-action@4942be832ce7ef18a53377d117a5e5aa5c47e86b
  uses: burtonr/octopus-cli-action@7.4.4
  with:
    # The full URL of your OctopusDeploy server
    server: # optional
    # The API key generated by your OctopusDeploy server
    apiKey: # optional
    # Used when passing credentials and not an API key
    username: # optional
    # Used when passing credentials and not an API key
    password: # optional
    # The command and parameters to use with the CLI
    command: # optional, default is --help
                      - name: Wait/watch an execution task in Octopus Deploy
  # You may pin to the exact commit or the version.
  # uses: OctopusDeploy/await-task-action@df7319c026caef02341eb8b702771276b3c445f3
  uses: OctopusDeploy/await-task-action@v3.0.2
  with:
    # The execution task ID to watch/wait for.
    server_task_id: 
    # How frequently, in seconds, to check the status.
    polling_interval: # optional, default is 10
    # Duration, in seconds, to allow for completion before timing out.
    timeout_after: # optional, default is 600
    # Whether to hide the progress of the task.
    hide_progress: # optional
    # The instance URL hosting Octopus Deploy (i.e. "https://octopus.example.com/"). The instance URL is required, but you may also use the OCTOPUS_URL environment variable.
    server: # optional
    # The API key used to access Octopus Deploy. An API key is required, but you may also use the OCTOPUS_API_KEY environment variable. It is strongly recommended that this value retrieved from a GitHub secret.
    api_key: # optional
    # The name of a space within which this command will be executed. The space name is required, but you may also use the OCTOPUS_SPACE environment variable.
    space: # optional
          
